//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.LeafService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.leaves", Namespace="http://schemas.datacontract.org/2004/07/Model.ModelObjects")]
    public enum Enumsleaves : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        category = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Auth = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ageBarrier = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        language = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        status = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        all = 10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LeavesList", Namespace="http://schemas.datacontract.org/2004/07/Model.ModelLists", ItemName="Leaf")]
    [System.SerializableAttribute()]
    public class LeavesList : System.Collections.Generic.List<Web.LeafService.Leaf> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Leaf", Namespace="http://schemas.datacontract.org/2004/07/Model.ModelObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.Auth))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.Language))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.Status))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.AgeBarrier))]
    public partial class Leaf : Web.LeafService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.LeafService.LeafType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.LeafService.LeafType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.LeafType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.Leaf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.Auth))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.Language))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.Status))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.LeafService.AgeBarrier))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeafType", Namespace="http://schemas.datacontract.org/2004/07/Model.ModelObjects")]
    [System.SerializableAttribute()]
    public partial class LeafType : Web.LeafService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auth", Namespace="http://schemas.datacontract.org/2004/07/Model.ModelObjects")]
    [System.SerializableAttribute()]
    public partial class Auth : Web.LeafService.Leaf {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Model.ModelObjects")]
    [System.SerializableAttribute()]
    public partial class Category : Web.LeafService.Leaf {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/Model.ModelObjects")]
    [System.SerializableAttribute()]
    public partial class Language : Web.LeafService.Leaf {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/Model.ModelObjects")]
    [System.SerializableAttribute()]
    public partial class Status : Web.LeafService.Leaf {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgeBarrier", Namespace="http://schemas.datacontract.org/2004/07/Model.ModelObjects")]
    [System.SerializableAttribute()]
    public partial class AgeBarrier : Web.LeafService.Leaf {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeafService.ILeafService")]
    public interface ILeafService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeafService/selectLeaves", ReplyAction="http://tempuri.org/ILeafService/selectLeavesResponse")]
        Web.LeafService.LeavesList selectLeaves(Web.LeafService.Enumsleaves leaftype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeafService/selectLeaves", ReplyAction="http://tempuri.org/ILeafService/selectLeavesResponse")]
        System.Threading.Tasks.Task<Web.LeafService.LeavesList> selectLeavesAsync(Web.LeafService.Enumsleaves leaftype);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeafServiceChannel : Web.LeafService.ILeafService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeafServiceClient : System.ServiceModel.ClientBase<Web.LeafService.ILeafService>, Web.LeafService.ILeafService {
        
        public LeafServiceClient() {
        }
        
        public LeafServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeafServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeafServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeafServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Web.LeafService.LeavesList selectLeaves(Web.LeafService.Enumsleaves leaftype) {
            return base.Channel.selectLeaves(leaftype);
        }
        
        public System.Threading.Tasks.Task<Web.LeafService.LeavesList> selectLeavesAsync(Web.LeafService.Enumsleaves leaftype) {
            return base.Channel.selectLeavesAsync(leaftype);
        }
    }
}
